[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["python3.11 -m pip install -r backend/requirements.txt"]

[start]
cmd = "python3.11 -c 'from backend.db import init_tables; init_tables()' && python3.11 -m gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --workers 1 --bind 0.0.0.0:$PORT backend.run:app"
